import ThemeRegistry from "@/theme/ThemeRegistry";
import "./globals.css";
import { Inter } from "next/font/google";
import StoreProvider from "@/StoreProvider";
import Layout from "@/components/header/Layout";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PCI INSPECTION",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <ThemeRegistry>
        <StoreProvider>
          <body >
            <Layout>
              {children}
            </Layout>
          </body>
        </StoreProvider>
      </ThemeRegistry>
    </html>
  );
}