import ThemeRegistry from "@/theme/ThemeRegistry";
import "./globals.css";
import { Inter } from "next/font/google";
import MenuAppBar from "@/components/header/Header";
import PciTabs from "@/components/tabs/Tabs";
import PciSideBar from "@/components/pci-sidebar/PciSideBar";
import StoreProvider from "@/StoreProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <ThemeRegistry>
        <StoreProvider>
        <body className={inter.className}  >
          <MenuAppBar />
          <div className="app">
            <PciSideBar />
            <main className="content">
              {children}
            </main>
          </div>
        </body>
        </StoreProvider>
      </ThemeRegistry>
    </html>
  );
}